---
title: "Lab 4"
author: "Eva Jason, Tannavee Kumar, Lizzy Mikita"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(tidyr)
library(readr)
```


```{r, message=F}
df1 = read_csv("https://raw.githubusercontent.com/xiaodan-zhou/pm25_and_disparity/refs/heads/main/data/data_part1.csv")
df2 = read_csv("https://raw.githubusercontent.com/xiaodan-zhou/pm25_and_disparity/refs/heads/main/data/data_part2.csv")
df3 = read_csv("https://raw.githubusercontent.com/xiaodan-zhou/pm25_and_disparity/refs/heads/main/data/data_part3.csv")
df4 = read_csv("https://raw.githubusercontent.com/xiaodan-zhou/pm25_and_disparity/refs/heads/main/data/data_part4.csv")
df5 = read_csv("https://raw.githubusercontent.com/xiaodan-zhou/pm25_and_disparity/refs/heads/main/data/data_part5.csv")

df_all = do.call(rbind, list(df1, df2, df3, df4, df5)) %>%
  filter(year >=2008)
```

```{r}
longer = select(df_all, year, zcta, pct_blk, pct_hisp, pct_native, pct_asian, 
                pct_white, black_pop, hisp_pop, native_pop, asian_pop, 
                white_pop, pm25) %>%
  drop_na() %>%
  pivot_longer(-c(zcta, year, pm25,black_pop, hisp_pop, native_pop, asian_pop, 
                  white_pop), names_to = "group_pct", values_to = "pct") %>%
  pivot_longer(-c(zcta, year, pm25, group_pct, pct), names_to = "group_pop", 
               values_to = "pop") 
```

```{r}
summary = group_by(longer, group_pop, year) %>%
  summarize(avg_pct = weighted.mean(pct, pop))
```

```{r}
df1 = merge(summary, longer)

df2 = mutate(df1, lrgr_avg = ifelse(pct > avg_pct, T, F)) %>%
  filter(lrgr_avg)

df3 = group_by(df2, group_pop, year) %>%
  summarize(avg_pm25 = weighted.mean(pm25, pop))

df_all_avg = group_by(df2, year) %>%
  summarize(avg_pm25 = weighted.mean(pm25, pop)) %>%
  mutate(group_pop = "all")

#df3 = rbind(df3, df_all_avg)
```

```{r}
ggplot() +
  geom_line(df3, mapping = aes(x = year, y = avg_pm25, color = group_pop, alpha = 0.1), linewidth=1) +
  geom_line(df_all_avg, mapping = aes(x = year, y = avg_pm25), linewidth=1.1) +
  theme_minimal() +
  ggtitle("PM 2.5 for different communities during the Obama Administration") +
  xlab(NULL) +
  ylab(NULL) + 
  theme(legend.position="none") +
  annotate("text",x = 2016.3, y = filter(df3, group_pop == "asian_pop", year == "2016")[[3]]-.2, label="Asian") +
  annotate("text",x = 2016.3, y = filter(df3, group_pop == "black_pop", year == "2016")[[3]], label="Black") +
  annotate("text",x = 2016.3, y = filter(df3, group_pop == "white_pop", year == "2016")[[3]], label="White") +
  annotate("text",x = 2016.3, y = filter(df3, group_pop == "native_pop", year == "2016")[[3]], label="Native") +
  annotate("text",x = 2016.4, y = filter(df3, group_pop == "hisp_pop", year == "2016")[[3]]+0.25, label="Hispanic") +
  annotate("text",x = 2016.1, y = filter(df_all_avg, year == "2016")[[2]], label="All") +
  scale_x_continuous(breaks=c(2008, 2010, 2012, 2014, 2016))# +
  #ylim(c(6,14)) +
  #scale_y_continuous(breaks = c(7:13))
```

```{r}
df_all_avg = group_by(df2, year) %>%
  summarize(avg_pm25_all = weighted.mean(pm25, pop)) %>%
  mutate(group_pop = "all") %>%
  select(-group_pop)

diff = merge(df_all_avg, df3) %>%
  mutate(diff = avg_pm25_all - avg_pm25)
```

```{r}
ggplot(diff, mapping = aes(x = year, y = diff, color = group_pop, alpha = 0.1), linewidth=1) +
  geom_line() +
  geom_line() +
  theme_minimal() +
  ggtitle("PM 2.5 for different communities during the Obama Administration") +
  xlab(NULL) +
  ylab(NULL) + 
  theme(legend.position="none")# +
  #annotate("text",x = 2016.3, y = filter(df3, group_pop == "asian_pop", year == "2016")[[3]]-.2, label="Asian") +
  #annotate("text",x = 2016.3, y = filter(df3, group_pop == "black_pop", year == "2016")[[3]], label="Black") +
  #annotate("text",x = 2016.3, y = filter(df3, group_pop == "white_pop", year == "2016")[[3]], label="White") +
  #annotate("text",x = 2016.3, y = filter(df3, group_pop == "native_pop", year == "2016")[[3]], label="Native") +
  #annotate("text",x = 2016.4, y = filter(df3, group_pop == "hisp_pop", year == "2016")[[3]]+0.25, label="Hispanic") +
  #annotate("text",x = 2016.1, y = filter(df_all_avg, year == "2016")[[2]], label="All") +
  #scale_x_continuous(breaks=c(2008, 2010, 2012, 2014, 2016))
```




